use_frameworks!

target :PodsDependencies do
  pod 'Dependency', path: 'Dependency'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['LD'] = '$(PROJECT_DIR)/../../../ld.py'
      config.build_settings['LIPO'] = '$(PROJECT_DIR)/../../../lipo.py'
    end
  end
end
